### ISSUE TITLE
problem while loading the data.

### ISSUE THREAD

**Issue by challakarthik9** [urmilkadakia/Ranking-of-academic-papers-and-authors#2]
![Screenshot (574)](https://user-images.githubusercontent.com/36627188/66695342-0c9cac80-ecde-11e9-86e7-a5219eff3ec1.png)
![Screenshot (575)](https://user-images.githubusercontent.com/36627188/66695343-0d354300-ecde-11e9-8a1a-cf49789da7f4.png)
![Screenshot (576)](https://user-images.githubusercontent.com/36627188/66695344-0d354300-ecde-11e9-8584-b4cfba20aaa8.png)
![Screenshot (573)](https://user-images.githubusercontent.com/36627188/66695341-0c9cac80-ecde-11e9-9fda-5407e280c816.png)
![Uploading Screenshot (574).png…]()
![Uploading Screenshot (575).png…]()
![Uploading Screenshot (576).png…]()

**Comment by challakarthik9** [comment]
can you please tell me the format of the dataset is it in CSV or tar or gz? how much size is the dataset!
there is a problem downloading the dataset please can you drop a link you're storage where I can download the dataset, please!

**Comment by urmilkadakia** [comment]
link to download dataset:
https://drive.google.com/file/d/17igB6eWXU7yIqAdNW529hw2k_5hlP2GO/view?usp=sharing

This is is the previous version of the V10 from the Aminer.org. This
dataset has been removed by Aminer.org, please try to use the newest
dataset as the older one has several issues.

**Comment by challakarthik9** [comment]
accept my request thank you!

**Comment by challakarthik9** [comment]
what format is the data stored gz , tar, text and csv ..in which format please brother can you help me!

**Comment by challakarthik9** [comment]
![Screenshot (606)](https://user-images.githubusercontent.com/36627188/66772591-afba1580-eeda-11e9-9be2-9c2dea470b5b.png)
still errors please help me

**Comment by challakarthik9** [comment]
can you send ur ipynb link with output also please
